#!/bin/sh

DESTINATION_DIRECTORY=/var/backups

echo "LUKS headers backup script by Paweł Wilk <pw@gnu.org>"
echo "-----------------------------------------------------"
echo "                         license: GNU GPL version 3.0"
echo

blkid | grep 'TYPE="crypto_LUKS"' | sort -u -t ' ' -k 2,2 | sort -r -t ' ' -k 1,1 | \
while read d uuid rest
do
	cryptname=""
	uuid=${uuid%\"*}
	uuid=${uuid##*\"}
	d=${d%%:*}

	# try names of matching devices from /etc/crypttab

	if [ -f /etc/crypttab ]; then
		for i in $(find -L /dev -samefile "${d}" 2>/dev/null); do
			l=$(grep "[[:blank:]]${i}[[:blank:]]" /etc/crypttab)
			[ -n "${l}" ] && break
		done
		cryptname="${l%%[\ $(printf '\t')]*}"
	fi

	# try active dm labels

	if [ -z "${cryptname}" -a -d /dev/mapper ]; then
		for i in $(find /dev/mapper -mindepth 1); do
			if cryptsetup -q status "${i}" 2>/dev/null | grep -q "device:[[:blank:]]*${d}[[:blank:]]*"; then
				cryptname="${i##*/}"
				break
			fi
		done
	fi

	# try md- aliases

	[ -z "${cryptname}" ] && cryptname=$(find -L /dev/md -samefile "${d}" 2>/dev/null)

	# try md- labels

        if [ -z "${cryptname}" ]; then
                cryptname=$(find -L /dev/disk/by-id -samefile "${d}" -name '*-name-*' 2>/dev/null)
                cryptname=${cryptname##*-}
                cryptname=${cryptname##*:}
        fi

	# fall back to device name

	[ -z "${cryptname}" ] && cryptname="${d}"

	cryptname=${cryptname##*/}
	printf "%s %-16s %s\t\tUUID=%s\n" '-' "${cryptname}" "${d}" "${uuid}"

	cryptsetup luksHeaderBackup --header-backup-file "${DESTINATION_DIRECTORY}/luks-header-uuid-${uuid}.img" "${d}"
	ln -fsr "${DESTINATION_DIRECTORY}/luks-header-uuid-${uuid}.img" "/var/backups/luks-header-${cryptname}"
done

exit 0

