#!/bin/sh

DESTINATION_DIRECTORY=/var/backups

echo "LUKS headers backup script by Paweł Wilk <pw@gnu.org>"
echo "-----------------------------------------------------"
echo "                         license: GNU GPL version 3.0"

if [ -n "${1}" ]; then
    DESTINATION_DIRECTORY="${1}"
else
    echo 										1>&2
    echo "WARNING: The backup files and passphrases valid at the time of backup"	1>&2
    echo "allow decryption of the LUKS data areas, even if the passphrases were later"	1>&2
    echo "changed or removed from the LUKS devices."					1>&2
    echo										1>&2
    echo "Pass destination directory path as a first argument to remove this warning."	1>&2
fi

echo
echo "Destination directory: ${DESTINATION_DIRECTORY}"
echo

blkid | grep 'TYPE="crypto_LUKS"' | sort -u -t ' ' -k 2,2 | sort -r -t ' ' -k 1,1 | \
while read d uuid rest
do
	LUKS_MAP_NAME=""
	uuid=${uuid%\"*}
	uuid=${uuid##*\"}
	d=${d%%:*}

	eval $(luks-determine-device "${d}")
	cryptname=${LUKS_MAP_NAME}

	# fall back to device name

	[ -z "${cryptname}" ] && cryptname="${d}"

	cryptname=${cryptname##*/}
	printf "%s %-16s %s\t\tUUID=%s\n" '-' "${cryptname}" "${d}" "${uuid}"

	cryptsetup luksHeaderBackup --header-backup-file "${DESTINATION_DIRECTORY}/luks-header-uuid-${uuid}.img" "${d}"
	ln -fsr "${DESTINATION_DIRECTORY}/luks-header-uuid-${uuid}.img" "${DESTINATION_DIRECTORY}/luks-header-${cryptname}"
done

exit 0

